# Generated by Django 4.2.4 on 2023-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CNPJ", models.CharField(max_length=14)),
                ("nome_razao", models.CharField(max_length=50)),
                ("nome_fantasia", models.CharField(max_length=50)),
                ("CNAE", models.CharField(max_length=255)),
            ],
        ),
    ]
