# Generated by Django 4.2.4 on 2023-08-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprises",
            name="CNPJ",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="enterprises",
            name="nome_fantasia",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
