# Generated by Django 4.2.4 on 2023-08-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_enterprises_cnpj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprises",
            name="CNPJ",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
