# Generated by Django 4.2.4 on 2023-08-10 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_enterprises_cnpj"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprises",
            old_name="CNAE",
            new_name="cnae",
        ),
        migrations.RenameField(
            model_name="enterprises",
            old_name="CNPJ",
            new_name="cnpj",
        ),
    ]
