# Generated by Django 4.2.4 on 2023-08-10 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_cnae_enterprises_cnae_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprises",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
