# Generated by Django 4.2.4 on 2023-08-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_enterprises_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprises",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
